[tool.poetry]
name = "ohheybrian"
version = "0.1.0"
description = "Homepage"
authors = ["Brian Bennett <brian.bennett2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.3.2"
htmx-flask = "^0.1.0"
python-dotenv = "^1.0.0"
jinja-partials = "^0.1.1"
webargs = "^8.2.0"
flask-migrate = "^4.0.4"
flask-sqlalchemy = "^3.0.3"
nh3 = "^0.2.13"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
