"""add comments model

Revision ID: 5095d0407d9f
Revises: 75c8fc20ddde
Create Date: 2023-11-22 20:32:25.791490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5095d0407d9f'
down_revision = '75c8fc20ddde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('occurred', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=128), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
