"""bool for comments which are replies

Revision ID: 55296ddc4f2a
Revises: a3a449714d6a
Create Date: 2024-03-14 21:28:53.064859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55296ddc4f2a'
down_revision = 'a3a449714d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reply', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('is_reply')

    # ### end Alembic commands ###
